[package]
name = "pandoras_box"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
clap = {version = "4.5.17", features = ["cargo"]}
futures = "0.3.30"
libc = "0.2.177"
thiserror = "1.0.63"
tokio = {version = "1.40.0", features = ["fs", "macros", "net", "rt-multi-thread", "sync", "time"]}
rustrc = { path = "../rustrc" }
log = "0.4.22"
chrono = "0.4.39"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
smolder_tools = { package = "smolder", path = "../../smolder/smolder-tools" }

[dev-dependencies]
env_logger = "0.11.5"

[profile.release]
opt-level = 3  # Optimize for size.
strip = true  # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
