[package]
name = "chimera"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
local-ip-address = "0.5.6"
netstat = "0.7.0"
clap = {version = "4.4.11", features = ["cargo"]}
reqwest = {version = "0.11.23", features = ["json"]}
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sys-info = "0.9.1"
sysinfo = "0.29.11"
tokio = { version = "1.34.0", features = ["fs", "macros", "rt-multi-thread"] }
which = "5.0.0"
wmi = "0.13.1"

[target.'cfg(target_os = "linux")'.dependencies]
pnet = "0.34.0"
procfs = "0.16.0"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
