name: Build Chimera Binary

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: i686-unknown-linux-musl
    
    - name: Install musl tools
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
    
    - name: Build Linux Target
      run: |
        cd chimera
        cargo build --target i686-unknown-linux-musl --release
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: chimera-linux-i686
        path: chimera/target/i686-unknown-linux-musl/release/chimera

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-gnu
    
    - name: Build Windows Target
      run: |
        cd chimera
        cargo build --target x86_64-pc-windows-gnu --release
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: chimera-windows-x64
        path: chimera/target/x86_64-pc-windows-gnu/release/chimera.exe
