name: Build Chimera Binary

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [i686-unknown-linux-musl, x86_64-pc-windows-gnu]
        include:
          - target: x86_64-pc-windows-gnu
            extension: .exe
          - target: i686-unknown-linux-musl
            extension: ""

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    
    - name: Build Target
      run: |
        cd chimera
        cross build --target ${{ matrix.target }} --release
        
    - name: Debug - List Files
      run: |
        echo "Listing release directory contents:"
        find chimera/target/${{ matrix.target }}/release -type f
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: chimera-${{ matrix.target }}
        path: chimera/target/${{ matrix.target }}/release/chimera${{ matrix.extension }}
        if-no-files-found: error

    - name: Upload Release Assets
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: chimera/target/${{ matrix.target }}/release/chimera${{ matrix.extension }}
