[package]
name = "download_embed_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
flate2 = "1.0.33"
md5 = "0.7.0"
quote = "1.0.37"
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls", "blocking"] }
syn = "2.0.77"
